# KNN

In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [7]:
df_han = pd.read_csv('/Users/scottlai/Documents/class/fall 2018/Stats479/project/data/dataset.csv',encoding='utf-8')
df_han.head()

,char,count,1,2,3,4,5,6,7,8,...,775,776,777,778,779,780,781,782,783,784
0,㐀,5,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,0.847059,0.847059,0.847059,0.847059,0.847059,0.847059,0.847059,0.835294,0.815686,0.784314
1,㐁,6,0.470588,0.545098,0.611765,0.65098,0.658824,0.654902,0.654902,0.654902,...,1.000000,1.000000,1.000000,1.000000,0.839216,0.435294,0.411765,0.749020,1.000000,1.000000
2,㐂,6,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
3,㐃,3,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,㐄,3,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

df_han = df_han[(df_han['count'] <= 30) & (df_han['count'] != 1)]
#print(df)

X = df_han.iloc[:, 2:28**2+2].astype(np.float)
y = df_han['count'].astype('category')
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.3,
                                                    random_state=123,
                                                    shuffle=True)

from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=35)
knn_model.fit(X_train, y_train)

y_pred = knn_model.predict(X_test)

num_correct_predictions = (y_pred == y_test).sum()
accuracy = (num_correct_predictions / y_test.shape[0]) * 100

print('Test set accuracy: %.2f%%' % accuracy)

Test set accuracy: 21.23%

In [83]:
#pca

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X)
new_han = pca.fit_transform(X)
X_train = pca.fit_transform(X_train)  
X_test = pca.transform(X_test)  
explained_variance = pca.explained_variance_ratio_ 


from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=50, random_state=0)  
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred1 = classifier.predict(X_test) 

from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

num_correct_predictions1 = (y_pred1 == y_test).sum()
accuracy1 = (num_correct_predictions / y_test.shape[0]) * 100

print('Test set accuracy: %.2f%%' % accuracy1)

Test set accuracy: 21.23%